server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: 'P@ŝw0rd'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka